<!DOCTYPE html>
  <html>
    <head>
      <title>Zedaeth Profile</title>
      <style>
        background-color: black;
        color: blue;
      </style>
    </head>
    <body>
      <p>Hello World!</p>
    </body>
  </html>
